import Head from 'next/head'
import Image from 'next/image'
import useProtectedPage from './../hooks/useProtectedPage';

export default function Home() {
  useProtectedPage()
  return (
    <>
      <Head>
        <title>Gerador de Documentos | CASAL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/casal_favicon.png" />
      </Head>
      <main>

      </main>
    </>
  )
}
