import Head from 'next/head'
import Image from 'next/image'
import useProtectedPage from './../hooks/useProtectedPage';
import { useEffect } from 'react';
import { useState } from 'react';
import UserCard from './../components/UserCard';
import FilesCard from '../components/FilesCard';

const baseUrl = process.env.NEXT_PUBLIC_SERVER_BASE_URL

export default function Home() {
  useProtectedPage()
  const [userInfo, setUserInfo] = useState<any>({})
  const [files, setFiles] = useState<any[]>([])

  useEffect(() => {
    const token = localStorage.getItem('token')?.toString()

    const content = {
      headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
          'Authorization': `${token}`
      },
      method: 'GET',
    }

    const getData = async () => {
      const data = await fetch(`${baseUrl}/current`, content)
      const user = await data.json()
      

      const filesData = await fetch(`${baseUrl}/files/${user.id}`, content)
      const files = await filesData.json()

      setFiles(files.files)
      setUserInfo(user)
    }

    getData()
  }, [])
  return (
    <>
      <Head>
        <title>Gerador de Documentos | CASAL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/casal_favicon.png" />
      </Head>
      <main className="px-4 lg:px-0 max-w-screen-xl mx-auto my-10 flex items-start justify-between gap-8">
        <div className='flex flex-col items-start justify-start gap-y-8 w-2/5'>
        <UserCard user={userInfo} />
        <FilesCard user={userInfo} files={files} />
        </div>
        <div className='w-full h-screen border-l-2 flex flex-col items-start'>
          <h1 className='text-2xl font-mono antialiased font-semibold ml-4'>Escolha o modelo e crie seu arquivo.</h1>
          <div className='ml-4 mt-4 flex justify-between align-center w-full'>
            <div className='flex items-center justify-center'>
              <label htmlFor="modelo" className="font-mono text-md font-light">Modelo: </label>
              <select name="modelo" id="modelo" className='bg-gray-200 w-44 rounded-lg ml-2 '>
                <option value=""></option>
                <option value="example">Exemplo</option>
              </select>
            </div>
            <div className='flex items-center justify-center '>
              <label htmlFor="modelo_nome" className="font-mono text-md font-light">Nome: </label>
              <input type="text" id='nome' name='nome' className='bg-gray-200 w-44 h-6 rounded-lg ml-4' />
            </div>
            <div className='flex items-center justify-center'>
              <input type="radio" id="protected" name="protected" value="protected" />
              <label htmlFor="protected" className="font-mono text-md font-light ml-4">Arquivo Protegido</label>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
