import Head from 'next/head'
import { useEffect } from 'react';
import useProtectedPage from '../hooks/useProtectedPage';
import { useState } from 'react';
import UserCard from '../components/UserCard';
import useForm from '../hooks/useForm';
import Link from 'next/link';

const getUsers = async (page = 1, name = '') => {
    const token = localStorage.getItem('token');

    const content = {
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Authorization': `${token}`
        },
        method: 'GET',
    }

    const data = await fetch(`${process.env.NEXT_PUBLIC_SERVER_BASE_URL}/users?page=${page}&name=${name}`, content)
    const response = await data.json()

    if (response) {
        return response
    } 

}

export default function Users () {
    useProtectedPage()

    const [users, setUsers] = useState<any[]>([])
    const [page, setPage] = useState(1)
    const [form, onchange, clear] = useForm({name: ''})

    useEffect(() => {
        getUsers()
        .then((response) => {
            setUsers(response)
        })
        .catch((err) => {
            console.log(err)
        })
    }, [])

    const renderUsers = users.map((user) => {
        return (
            <>
                <Link href={`/user/${user.id}`} passHref >
                    <div className='cursor-pointer hover:bg-gray-200 rounded-xl'>
                        <UserCard user={user} key={user.id} />
                    </div>
                </Link>
            </>
        )
    }) 

    const onSubmitSearch = async (e: any) => {
        e.preventDefault()

        const users = await getUsers(page, form.name)

        setUsers(users)
    }
    return (
        <>
            <Head>
                <title>Gerador de Documentos | CASAL | Buscar Usuários</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/casal_favicon.png" />
            </Head>
            <main className="px-4 lg:px-0 max-w-screen-xl mx-auto my-10 flex flex-col items-start justify-start gap-8">
                <form className='w-full flex items-center justify-center' onSubmit={onSubmitSearch}>
                    <label htmlFor="name" className="font-mono text-md font-light">Busque por nome: </label>
                    <input type="text" name="name" id="name" placeholder='Nome...' value={form.name} onChange={onchange} className='bg-gray-200 w-44 h-6 rounded-lg ml-4' />
                </form>
                <div className='flex flex-wrap items-start justify-between gap-8'>
                    {users && renderUsers}
                </div>
            </main>
        </>
    )
}